### ISSUE TITLE
Show gas refund in gas calculator

### ISSUE THREAD

**Issue by frangio** [comitylabs/evm.codes#109]
For SSTORE it would be great to see the gas refund in the calculator results.

This could be an additional result shown below "static gas + dynamic gas":

![image](https://user-images.githubusercontent.com/481465/151420992-e051d2fb-fb3c-47f9-ad4a-38de9b71d094.png)

**Comment by peroket** [comment]
@frangio see the PR #111 to add that functionality :-)

**Comment by peroket** [comment]
@frangio feature is now deployed :-)

**Comment by frangio** [comment]
This will be great, thank you!
