### ISSUE TITLE
Hardfork name is wrong in Gas Refunds description.

### ISSUE THREAD

**Issue by 0xys** [comitylabs/evm.codes#114]
In the gas refund section of the about page, https://www.evm.codes/about, it says the following two revises in refund logic is applied after **Berlin** hardfork while it actually is **London**, more specifically by [EIP3529](https://eips.ethereum.org/EIPS/eip-3529).
- gas quotient is reduced to `5` to `2`
- `SELFDESTRUCT` doesn't trigger gas refund

**Comment by 0xys** [comment]
Thanks for quick response.
I created PR. https://github.com/comitylabs/evm.codes/pull/115

**Comment by dorlevi** [comment]
Thanks again, forgot to close this!
