### ISSUE TITLE
Ambiguity in storage gas costs

### ISSUE THREAD

**Issue by hrkrshnn** [comitylabs/evm.codes#118]
![image](https://user-images.githubusercontent.com/13174375/154812935-0878f1bb-e623-4e99-9b9e-d8bd90305542.png)

In the above case, the 'key' can never be cold. So the option for that should be disabled.

**Comment by peroket** [comment]
Thank you, we will look into it.

**Comment by dorlevi** [comment]
thanks again @hrkrshnn for reporting
