### ISSUE TITLE
Feature request: support URL query strings for opcode searches

### ISSUE THREAD

**Issue by maurelian** [comitylabs/evm.codes#122]
First, this site is amazing, thank you for continuing to improve it!

**Request:** I would _love_ to be able automate a quick opcode (or precompile) search using a format like `https://www.evm.codes/search?fork=arrow-glacier&opcode={query}`. Where the fork defaults to the current `live` value.

I'd use this site on a daily basis if it were that easy. :)

**Comment by dorlevi** [comment]
Yep, I see how this would be handy to quickly search without using the site, we are pretty heads down on our core product but we will keep this in mind, seems like a good starter project to onboard a frontend/full-stack while letting them read more about the EVM :) 

If there is a front/end-full-stack engineer who sees it and wants to pick this up we will compensate them, in general, if you know someone who would want to help us improve this and work  on some other opensource utilities free we have in mind on a part-time or even fulltime basis we would love to talk to them

**Comment by Saw-mon-and-Natalie** [comment]
I would love to help with this feature. 

@maurelian, do you want that endpoint to work kind of as an API? Like return data in `JSON` format. Also what date you would it to return? (opcode, name, gas, stack slots consumed, stack slots produced, description, ...)

**Comment by peroket** [comment]
Thanks @Saw-mon-and-Natalie 
I guess the first step would be to add the fork in the link to opcodes, because I realise now that it is missing. That should not be too hard, if you want to start with that?

For example when I click on the first link to opcode 00, I get https://www.evm.codes/#00, would be even better with the fork.

**Comment by Saw-mon-and-Natalie** [comment]
Should the link be like ` https://www.evm.codes/#00?fork=arrow-glacier` even though the `fork` query is not being used?

**Comment by peroket** [comment]
The idea would be to add also setting the fork according to the parameter (or leave the current behaviour if there is none).

**Comment by iFrostizz** [comment]
any progress on this feature ?

**Comment by dorlevi** [comment]
we have not worked/prioritized it, but if someone submits a PR we will review and merge it.

**Comment by thevaizman** [comment]
@maurelian I merged a PR that contains the changes described in your original post :)
Closing this issue for now.

**Comment by maurelian** [comment]
Amazing, TY!
