### ISSUE TITLE
`JUMPI`'s note about valid jump destinations is incorrect

### ISSUE THREAD

**Issue by SamWilsn** [comitylabs/evm.codes#129]
As far as I can tell, `JUMPI` only checks if the destination if the jump would be taken, so this note is incorrect:

> The error is generated even if the JUMP would not have been done.

See: https://github.com/rust-blockchain/evm/security/advisories/GHSA-pvh2-pj76-4m96

**Comment by peroket** [comment]
Thanks, our Javascript VM has the same issue, we are going to investigate to change that.
