### ISSUE TITLE
EXTCODEHASH gas costs

### ISSUE THREAD

**Issue by 0xalpharush** [comitylabs/evm.codes#140]
The cost of EXTCODEHASH is currently set to 100 and indicates a dynamic cost. However, AFAICT the gas cost should be a constant amount of 700 as of EIP-1884. Where does this information come from? Perhaps it should be changed. 
Geth params:
https://github.com/ethereum/go-ethereum/blob/8798cd3a09d693ce038fa4a2a93348d3de010d72/params/protocol_params.go#L105
Geth gas function:
https://github.com/ethereum/go-ethereum/blob/8798cd3a09d693ce038fa4a2a93348d3de010d72/core/vm/jump_table.go#L143-L145

**Comment by peroket** [comment]
It comes from reading the code of the evm js, but can very well have been done incorectly.
Thanks for notifying us, will take a look to fix it.

**Comment by jonahcui** [comment]
In fork Istanbul, the gas of EXTCODEHASH is 700. But after Berlin, the extcodehash calculate has been changed.

The eip:  https://eips.ethereum.org/EIPS/eip-2929

The code of go-ethereum's gas calculator: https://github.com/ethereum/go-ethereum/blob/d740d6e741562e98b3d75a98e7decdfee3bdd904/core/vm/operations_acl.go#L148

We use the ethereumjs to calculate the gas price. the method's code link is: https://github.com/ethereumjs/ethereumjs-monorepo/blob/a60b878c377a55cd17a6e633a59bc4400713eddb/packages/evm/src/opcodes/gas.ts#L156

So, you can switch the fork to berlin. You can see the static gas of extcodehash is 700.

**Comment by dorlevi** [comment]
doing some housekeeping; @0xalpharush, @jonahcui (thank you!!) covered it and I'll close the ticker
