### ISSUE TITLE
[playground] Switching from bytecode to mnemonic (and viceversa and other combination) should "translate" to the destination language

### ISSUE THREAD

**Issue by StErMi** [comitylabs/evm.codes#145]
Hi there, 

As a dev/user, I would expect that if I've inputted a bytecode inside the playground, run it, and then I switch to the mnemonic version it would show me the mnemonic version of the bytecode.

Currently, it does not that, and it forces me to go to an external tool, translate it and then paste it again. 
It would be really nice if this feature is enabled by default for all the various language  (yul, solidity, bytecode, mnemonic)

**Comment by peroket** [comment]
That's a very good idea yes, thank you.
I don't think we can support conversions to yul or solidity, but to opcodes and mnemonic definitely.

**Comment by jonahcui** [comment]
@malexw Had you started to do this feature? if you don't have time, I can do this.

**Comment by malexw** [comment]
@jonahcui Nope, I haven't had a look at it. It's all yours!

**Comment by peroket** [comment]
> @peroket @dorlevi I had finished this in the commit [7963495](https://github.com/jonahcui/evm.codes/commit/79634959a4b2285afc8b4e095a122589b68c6713)
> 
> But I found a problem:
> 
> * I compile the `yul` contract and run it.
> * Then, I change the code type to bytecode and do nothing.
> * Then, I change the code type to the mnemonic. I will change the code in the editor to the opcodes of the contract that I compile the `yul` contract.
>   Same issues when switching to bytecode from mnemonic.
> 
> Whether we need to fix this problem? If we don't need to fix this problem. I will pull the request.

I'm not sure I understand the problem? If when you switch it changes opcode to mnemonics and back, sounds like what we want. Maybe better though, having a button "translate", that will show the possible options. So for solidity and yul, there would be opcodes and mnemonics, and for opcode and mnemomics, jst the other one. That way everything is explicit and it's not weird when I switch from opcode to yul for example.

What do you think? Also feel free to open a PR so that we can play with it :-)

**Comment by jonahcui** [comment]
Oh
It just means I will translate yul to mnemonics or bytecode. The code will show Yul's bytecode. When you first switch to yul, then switch to mnemonics, and then switch to bytecode.

**Comment by devtooligan** [comment]
thanks for workimg on this @jonahcui

I see what you're saying about Yul to bytecode.  I think that's ok for now.  You went above and beyond the original request of this ticket which is to just translate between byte code and mneumonics.  I think thistranslation alone will help a lot of people, can we move forward with getting this merged (either with or without the Yul functionality) ?

**Comment by dorlevi** [comment]
Sorry, malexw is not working on this project anymore and was on the review, I'm happy to merge now and agree @jonahcui has gone above and beyond (thank you!!!) I think he mentioned he wanted to do some [additional changes ](https://github.com/comitylabs/evm.codes/pull/152) but we can merge now and deal with them later

**Comment by dorlevi** [comment]
Closing this as the PR was [merged](https://github.com/comitylabs/evm.codes/pull/152)
