### ISSUE TITLE
Playground: sending wei/ether does not work

### ISSUE THREAD

**Issue by snreynolds** [comitylabs/evm.codes#155]
Trying to send X wei but callvalue() returns 0

**Comment by snreynolds** [comment]
Here is a link to the playground that reproduces it. In the "value to send" input box at the bottom, I am sending 10000 wei to but calling callvalue() does not load that value. See playground [here](https://www.evm.codes/playground?callValue=1000000&unit=Wei&codeType=Yul&code=%27(z~~let%20val%20%3A%3D%20callvalue%7By~~sstore%7B1%2C%20valy)%27~%20%20z%5Cny%7Dz%01yz~_) to reproduce!

**Comment by peroket** [comment]
Was fixed along #148
