### ISSUE TITLE
Need to update the DIFFICULTY opcode (now PREVRANDAO after the merge)

### ISSUE THREAD

**Issue by karmacoma-eth** [comitylabs/evm.codes#172]
See https://eips.ethereum.org/EIPS/eip-4399

I'm happy to contribute updated EVM reference docs if that's helpful

**Comment by dorlevi** [comment]
@karmacoma-eth, quick update: 

@thevaizman picked this up _(trying his first FE contribution)_; besides updating the reference, we also wanted to ensure the playground has support for the opcode/new behavior and updating to the latest Etherjs, which sadly [introduced a bug with the playground](https://github.com/ethereumjs/ethereumjs-monorepo/issues/2290) so we want to give it a few days to see what they say.

**Comment by thevaizman** [comment]
@karmacoma-eth another update on the status of this issue:

While I managed to patch their source code and run the build locally and test that everything is working fine, I ran into some problems building the app using the new  version of the `@ethereumjs/evm` library that causes build errors.
I opened [yet another issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/2295) on their Github, and I am now waiting for the devs response.
Will update as soon as this gets resolved.

**Comment by thevaizman** [comment]
@karmacoma-eth After a long wait, due to multiple issues we had with our major external dependency, we can finally close this issue as it was addressed in this [PR](https://github.com/comitylabs/evm.codes/pull/180).

Sorry it took so long :)
