### ISSUE TITLE
Incorrect stack item padding

### ISSUE THREAD

**Issue by rodrigoherrerai** [comitylabs/evm.codes#197]
Hi, 

There seems to be an error with the way evm.codes does the padding. 

For example, 

If we have a function with one argument (an address) and we load it to the stack: 

addr = 0xb172f70266cF082EB38C0B7FDE42fe5c8028429A

```
0x04 calldataload
```

We get the following stack output: 
b172f70266cf082eb38c0b7fde42fe5c8028429a000000000000000000000000

It is in reversed order (compared to foundry and remix). 

We should be getting: 
000000000000000000000000b172f70266cf082eb38c0b7fde42fe5c8028429a

**Comment by thevaizman** [comment]
hey @rodrigoherrerai,

i'm not sure why you see an error with the current behavior of `calldataload` - what it does is copy 32-bytes of data from the calldata you provided to the call.
if the calldata ends before it reads 32-bytes, it will _**right**_ pad the value with zeroes - hence the right padded value you see pushed to the top of the stack as a result.

you can refer to the opcode definition [here](https://www.evm.codes/#35?fork=merge) and see the examples for more details :)
