### ISSUE TITLE
CALLDATACOPY

### ISSUE THREAD

**Issue by veridelisi** [comitylabs/evm.codes#204]
Hi
I think you need to change "**CALLDATACOPY sample**".

**CALLDATA** adress must be as follows
0x**CC**FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF**AABBCCDDEE**

**input 1** must be
PUSH1 2
PUSH1 30
PUSH1 0
CALLDATACOPY

**input 2** must be
PUSH1 1
PUSH1 0
PUSH1 0
CALLDATACOPY

Sincerely
VeriDelisi

**Comment by peroket** [comment]
Hello thank you for your feedback :-)
Can you explain what is the problem and how your proposal is a solution to it? I must admit, I fail to understand what you are proposing.

**Comment by veridelisi** [comment]
Hi peroket

Opcodes, 37, CALLDATACOPY page, 
you use **Calldata** as **0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF**
And you use **input 2** as **(0,31,8)**

![sample](https://user-images.githubusercontent.com/72710290/211760497-48a943ea-4830-4285-b174-5791836eacff.JPG)

Problem is that:

User cant understand what is going on with this Calldata and input 2's variables because _your calldata is filling with F_.

My advice is

you use call data as "**0xCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAABBCCDDEE**"
and you use **input 2** as **(1,0,0)** and  **input 1** as **(2,30,0)**

**Comment by peroket** [comment]
So this is for clarity, understood, thank you :-)
Feel free to do the change yourself, otherwise I will do it later.

**Comment by jonahcui** [comment]
I have changed the code, and the page has been changed as below:
<img width="758" alt="CleanShot 2023-01-12 at 11 51 00@2x" src="https://user-images.githubusercontent.com/101780038/211971798-6e1fee6d-fef0-40cf-8169-6f67cfb339aa.png">

But I still need to post the pr. If you like it, I will post it.

**Comment by peroket** [comment]
Can we keep the inputs closer to the original ones, maybe? The important things to show, I think, is that it writes for the given length (not overwriting the rest), and that reading out of bounds makes it write 0s. So making the first write bigger than the second, and making the second read out of bounds but not overwriting the whole memory we just wrote, I think it shows well the behaviour :-)
Plus the change in the input to make it more clear which bytes are copied, and this is perfect :-)
