### ISSUE TITLE
Define stack top and bottom

### ISSUE THREAD

**Issue by lightclient** [comitylabs/evm.codes#208]
One rough edge of evm.codes is that I never remember the ordering of the operands. I would like the column header "stack input" to also say "top -> bottom" so it's clear always the order.

**Comment by peroket** [comment]
Thank you for your suggestion. You can click on an opcode, and there the input order is given explicitly.

**Comment by dorlevi** [comment]
sorry, we had it open for awhile and didn't prioritize it so I guess we should close now. thanks again for the suggestion
