### ISSUE TITLE
mload doesn't cause memory expansion

### ISSUE THREAD

**Issue by codeislight1** [comitylabs/evm.codes#213]
in the memory expansion section in about page, the `mload` need to be replaced with `mstore`, since mstore is the one that cause memory expansion and not mload.

`Any opcode that accesses memory may trigger an expansion (such as [MLOAD](https://www.evm.codes/#51), [RETURN](https://www.evm.codes/#F3) or [CALLDATACOPY](https://www.evm.codes/#37)).`

link to the page:
https://www.evm.codes/about?fork=merge

**Comment by peroket** [comment]
MLOAD does trigger memory expansion as well.
You can see in EthereumJS the MLOAD instruction: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/evm/src/opcodes/functions.ts#L660
Which calls memory extend even on reads, thus having to pay the cost of that https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/evm/src/memory.ts#L68

**Comment by codeislight1** [comment]
my bad, thanks for the clarification!
