### ISSUE TITLE
EXP operation bug.

### ISSUE THREAD

**Issue by zydjohnHotmail** [comitylabs/evm.codes#222]
Hello:
I have tried a few EVM code, most of them works, but for operation "EXP", there is a bug:
PUSH1 1
PUSH1 2
EXP
PUSH1 0x20
MSTORE
PUSH1 32
PUSH1 0x20
RETURN
The result of 1**2 should always be 1, no matter how big the second number is, but I got the result: 2.
Another example:
PUSH1 5
PUSH1 2
EXP
PUSH1 0x20
MSTORE
PUSH1 32
PUSH1 0x20
RETURN
The result of 5**2 should be 25, but I got 10 (5 * 2 = 10; but 5 ** 2 = 25)!
It seems the code use multiple in stead of exponent in  this operation.
Please take a look and fix it ASAP.
Thanks,

**Comment by peroket** [comment]
Hello,

I think you are mixing the order of parameters. The first push will be the second element of the stack, thus it will be the exponent, as you can see https://www.evm.codes/#0a?fork=merge. Your first program is correctly return 2**1, which is 2.

Running your second example I do not get 10 however, I get 32, which is the expected result of 2**5.

Does that solve you issue?

**Comment by zydjohnHotmail** [comment]
Hi,
Please show me your EVM code, I want to calculate the 5^2 or (5*5 = 25); I don't need 2^5=32.

**Comment by peroket** [comment]
You need to give the parameters in the correct order: https://www.evm.codes/playground?fork=merge&unit=Wei&codeType=Mnemonic&code='y2~5zEXPwMSTORE~32wRETURN'~zyz%5CnyPUSH1%20w~0x20z%01wyz~_ 
Note that the numbers are in hex.

**Comment by zydjohnHotmail** [comment]
OK, thanks. I understand it now!
