### ISSUE TITLE
ecPairing with empty calldata produces bug in the memory field of the playground

### ISSUE THREAD

**Issue by OlivierBBB** [comitylabs/evm.codes#228]
Executing the following bytecode in the playground
```
PUSH1 0x20
PUSH1 0
PUSH1 0
PUSH1 0
PUSH1 0       // value
PUSH1 8       // address
PUSH2 0xffff  // gas
CALL
```
Produces the following memory
```
    0000000000000000000000000000000000000000000000000000000000000001000000...000000000
```
containing 16383 zeros and a single 1 (at byte offset 32, as expected.) See screenshot:

![image](https://user-images.githubusercontent.com/38285177/232839951-299ee9df-f57a-49c1-b57c-bda4bf83734f.png)

The correct representation of memory should be

```
    0000000000000000000000000000000000000000000000000000000000000001
```

**Comment by peroket** [comment]
Thank you for letting us know we will look into it :-)
