### ISSUE TITLE
"Invalid EVM version requested." error in playground when using Shanghai fork

### ISSUE THREAD

**Issue by ardislu** [comitylabs/evm.codes#229]
Steps to reproduce the issue:
1. Go to https://www.evm.codes/playground?fork=shanghai
2. Change the language to "Solidity"
3. Press "Run" on the prepopulated code

Expected result: the code compiles successfully

Actual result: the code fails to compile and the following error appears in the console:

```
Loading Solidity compiler v0.8.19...
Solidity compiler loaded
Starting compilation...
[Error] Invalid EVM version requested.
```

Workaround: switching to an earlier fork fixes the issue (e.g. https://www.evm.codes/playground?fork=merge works as expected).

---

For reference, here's the Solidity code that is prepopulated when I switch the language to Solidity:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.3;

contract Counter {
    uint public count;

    // Function to get the current count
    function get() public view returns (uint) {
        return count;
    }

    // Function to increment count by 1
    function inc() public {
        count += 1;
    }

    // Function to decrement count by 1
    function dec() public {
        count -= 1;
    }
}
```

**Comment by peroket** [comment]
Thank you, will look into it :-)
