### ISSUE TITLE
Add more gas cost information

### ISSUE THREAD

**Issue by peroket** [comitylabs/evm.codes#57]
For each opcode with a runtime component to the gas cost, add the editable formula so that the full cost can be obtained, and the different conditions changed.

For example:
BALANCE [] warm [] cold: x cost (exclusive checkbox)
EXP 10 + 50 * [byte_len_exponent]: x cost (input field)

The constants can be obtained from ethereum-js, to stay up to date with version changes.

**Comment by assimovt** [comment]
Dynamic gas calculations are here: https://github.com/wolflo/evm-opcodes/blob/main/gas.md

**Comment by holgerd77** [comment]
Hi guys, Holger from EthereumJS here, just stumbled upon your project this morning, great work, just tweeted about it: https://twitter.com/EFJavaScript/status/1466391494495981574

Just to let you know: we have a PR on dynamic gas costs pretty much done here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1553. 🙂 

Some last things to be settled but this will otherwise be merged within days and relased along a new minor version during the next 1-2 weeks. Likely worth to wait on that, then you can take the functionality from there!

Also //cc-in in her @jochem-brouwer who has done the major work on this.

**Comment by dorlevi** [comment]
Amazing, well worth the wait. thanks @jochem-brouwer and @holgerd77

**Comment by peroket** [comment]
In our extra section we want to add the way the dynamic cost is computed, and to show an interactive way to get a final number. Here would be all the inputs we need for each opcodes in order to do that:

- EXP
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'expByte')
  * From user:
    - exponent (integer)
- SHA3
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'sha3Word')
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
  * From user:
    - offset (integer)
    - byte size (integer)
    - current memory size (integer)
- CALLDATACOPY, CODECOPY, RETURNDATACOPY
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'copy')
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
  * From user:
    - read offset (integer)
    - write offset (integer)
    - byte size (integer)
    - current memory size (integer)
- EXTCODECOPY: same as copy above +
  * Constants from ethereum js:
    - common.param('gasPrices', 'coldaccountaccess')
    - common.param('gasPrices', 'warmstorageread')
  * From user:
    - address warm or cold (exclusive choice)
- BALANCE, EXTCODESIZE, EXTCODEHASH
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'coldaccountaccess')
    - common.param('gasPrices', 'warmstorageread')
  * From user:
    - address warm or cold (exclusive choice)
- SLOAD
  * Constants from ethereum js:
    - common.param('gasPrices', 'coldsload')
    - common.param('gasPrices', 'warmstorageread')
  * From user:
    - key warm or cold (exclusive choice)
- SSTORE
  * Constants from ethereum js:
    - common.param('gasPrices', 'coldsload')
    - common.param('gasPrices', 'warmstorageread')
    - common.param('gasPrices', 'sstoreNoopGasEIP2200')
    - common.param('gasPrices', 'sstoreInitGasEIP2200')
    - common.param('gasPrices', 'sstoreCleanGasEIP2200')
    - common.param('gasPrices', 'sstoreDirtyGasEIP2200')
  * From user:
    - key warm or cold (exclusive choice)
    - value at key at the start of the transaction (integer)
    - previous value at key (integer)
    - new value at key (integer)
- LOG*
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'logTopic')
    - common.param('gasPrices', 'logData')
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
  * From user:
    - read offset (integer)
    - byte size (integer)
    - current memory size (integer)
- RETURN,REVERT,MLOAD,MSTORE,MSTORE8
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
  * From user:
    - read offset (integer)
    - byte size (integer) (only return and revert)
    - current memory size (integer)
- CALL*
  * Constants from ethereum js:
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
    - common.param('gasPrices', 'coldaccountaccess')
    - common.param('gasPrices', 'warmstorageread')
  * From user:
    - call value (integer) (not for delegate call and static call)
    - read offset (integer)
    - byte size (integer) (only return and revert)
    - current memory size (integer)
    - address warm or cold (exclusive choice)
    - is called account empty (boolean) (only for call)
    - gas sent with the call (integer)
- SELFDESTRUCT
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'coldaccountaccess')
    - common.param('gasPrices', 'warmstorageread')
    - common.param('gasPrices', 'callNewAccount')
  * From user:
    - call value (integer)
    - address warm or cold (exclusive choice)
    - is called account empty (boolean)
    - gas sent with the call (integer)
- INVALID (no param)
- CREATE*
  * Constants from ethereum js:
    - Static cost
    - common.param('gasPrices', 'memory')
    - common.param('gasPrices', 'quadCoeffDiv')
    - common.param('gasPrices', 'sha3Word') (create2 only)
  * From user:
    - read offset (integer)
    - byte size (integer)
    - current memory size (integer)

Probably some stuff missing/incorrect but that's a start :-)

**Comment by assimovt** [comment]
@peroket Thanks for adding the spec for all the inputs to calculate dynamic fees. I've just pushed #76 with an initial implementation of this feature. We can now start adding calculations similar to what [ethereumjs-vm#functions](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/opcodes/functions.ts) has, here is [one example for `EXP`](https://github.com/comitylabs/evm.codes/pull/76/files#diff-a2471e65433f6a191e9006070e0da2a5530196527bbb7b82e2821f01b608db95R29-R37) that I've already added.

**Comment by jochem-brouwer** [comment]
@assimovt As mentioned by @holgerd77, we have a branch (which is almost ready to get merged, there's one not super related test failing there) which extracts all dynamic gas from the functions file. See [this](https://github.com/ethereumjs/ethereumjs-monorepo/blob/vm-backwards-compatible-dynamic-gas-cost-refactoring/packages/vm/src/evm/opcodes/gas.ts) file :smile:

**Comment by assimovt** [comment]
@jochem-brouwer thanks for the link. Yep, we've looked into that PR, but all the functions are requiring a `runState` and hence the VM context? Whereas we're getting the inputs from the user, instead of popping them from the stack. Is there a way to use this utility file you've created and provide the inputs as args? Is this going to be a public API for the library?

**Comment by jochem-brouwer** [comment]
Ah right, I was merely pointing at it so there's a direct overview of each opcode which has dynamic costs, complete with the program to calculate these fees. We do not intend to expose this API, but I guess you /could/ hack around to use it. Then you'd need to generate a valid `runState` (convert user input to the right stack) and pass on a `gas` BN and a `Common` describing the fork you are on. But since we don't expose this API the interface could change any moment, so I would not recommend doing that - instead, use it as reference :smile:

**Comment by peroket** [comment]
> Ah right, I was merely pointing at it so there's a direct overview of each opcode which has dynamic costs, complete with the program to calculate these fees. We do not intend to expose this API, but I guess you /could/ hack around to use it. Then you'd need to generate a valid `runState` (convert user input to the right stack) and pass on a `gas` BN and a `Common` describing the fork you are on. But since we don't expose this API the interface could change any moment, so I would not recommend doing that - instead, use it as reference smile

Thanks, we will do that :-)

**Comment by peroket** [comment]
Things to do:
- [ ] Change the inputs to estimate the dynamic cost per fork
- [ ] Check placement of the estimate section, especially with lots of parameters like for CREATE
- [ ] Investigate if we can make visually clear which estimate parameters come from the stack and which come from the state
- [ ] Check problem with petersburg fork and SSTORE dynamic gas documentation
- [ ] Apply reference formula formatting to the "About" page

**Comment by peroket** [comment]
> @assimovt As mentioned by @holgerd77, we have a branch (which is almost ready to get merged, there's one not super related test failing there) which extracts all dynamic gas from the functions file. See [this](https://github.com/ethereumjs/ethereumjs-monorepo/blob/vm-backwards-compatible-dynamic-gas-cost-refactoring/packages/vm/src/evm/opcodes/gas.ts) file smile

Thank you @jochem-brouwer that file was a tremendous help :-)

**Comment by holgerd77** [comment]
Yeah, sorry, the release itself got a bit delayed, we have some behavior alignment question open between Geth/Hardhat/EthereumJS VM which needs to be settled before we can do the release.

Nothing grave but might take another 1-3 weeks I guess.

**Comment by holgerd77** [comment]
Hi there, just to let you know: we have now released the new EthereumJS VM [v5.7](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.7.0) which includes a `dynamicFee` field in the `step` event with the dynamic gas costs.

Generally feel free to open any issues on our repo if you have questions or comments on the VM usage (e.g. also on broader things like package/file sizes, browser compatiblity, ...).

**Comment by peroket** [comment]
thanks @holgerd77 I will check it :-)
