### ISSUE TITLE
Idea: add calldata field to add parameter input when executing opcodes

### ISSUE THREAD

**Issue by peroket** [comitylabs/evm.codes#59]

**Comment by fvictorio** [comment]
Besides calldata, it would be cool to be able to set the value (the result of `CALLVALUE`) too.

**Comment by fvictorio** [comment]
Btw, the reason I would like to have that is that it would make it more fun to solve these [EVM puzzles](https://github.com/fvictorio/evm-puzzles).

What's more, if there was some way to generate a link to the playground with a pre-filled bytecode, I could generate it for each puzzle. That would make it less of a chore to figure it out the solution.

**Comment by peroket** [comment]
> Btw, the reason I would like to have that is that it would make it more fun to solve these [EVM puzzles](https://github.com/fvictorio/evm-puzzles).
> 
> What's more, if there was some way to generate a link to the playground with a pre-filled bytecode, I could generate it for each puzzle. That would make it less of a chore to figure it out the solution.

That's a very good idea! Thanks for that. We will look into it.

**Comment by peroket** [comment]
@fvictorio I put your idea as a separate task https://github.com/comitylabs/evm.codes/issues/95
