### ISSUE TITLE
When hovering an opcode the highlight doesn't extend to the edge of the table

### ISSUE THREAD

**Issue by dorlevi** [comitylabs/evm.codes#69]
When you hover over an opcode, the "highlight" doesn't extend till the edge of the table (it doesn't cover the "expand column"), I believe it would look cleaner if it did extend to the full width of the table, which is also the behavior of the expanded info

 
<img width="1319" alt="Screen Shot 2021-11-25 at 7 41 00 AM" src="https://user-images.githubusercontent.com/1457950/143444398-f9666191-f9d7-44ee-a542-47b48e2fff76.png">

*reported by D

**Comment by assimovt** [comment]
Fixed in #66
