### ISSUE TITLE
Add "default stack order" to docs

### ISSUE THREAD

**Issue by charles-cooper** [comitylabs/evm.codes#88]
I always get confused whether the convention is top/leftmost stack item first or bottom/rightmost stack item first and have to remind myself by looking at an opcode whose ordering I know (`MSTORE`). It would be helpful to add a box at the top of the docs which says "leftmost item is the top of stack".

(Here's an example, `LT`, which is not super clear)
![Screenshot from 2021-12-26 16-03-54](https://user-images.githubusercontent.com/3867501/147420071-9951acf8-8197-4572-ac49-72ff7aac0375.png)

**Comment by peroket** [comment]
Would it be more clear if we add a third column with the stack item number?

**Comment by charles-cooper** [comment]
No because (at least for my tiny brain) I keep forgetting whether 1 means top or bottom of the stack. I think a note anywhere on the page saying "1 == top of stack" would do the trick though

**Comment by peroket** [comment]
I invite you to look at the changes and tell me if that helps you :-)
https://github.com/comitylabs/evm.codes/pull/91
Or the preview link directly: https://evm-codes-git-make-stack-order-more-clear-comity.vercel.app/

**Comment by charles-cooper** [comment]
It definitely helps!
